cmake_minimum_required(VERSION 2.8)
project(project-matterhorn)
include(common/settings.cmake)


add_executable(project-matterhorn ${COMMON_HEADERS} Config.h Window.cpp Texture.cpp HeightMap.cpp CameraPath.cpp Skybox.cpp Grid.cpp Shader.cpp ShaderProgram.cpp ShadowMap.cpp Camera.cpp noise_vshader.glsl noise_fshader.glsl skybox_vshader.glsl skybox_fshader.glsl terrain_vshader.glsl terrain_fshader.glsl shadow_fshader.glsl water_vshader.glsl water_fshader.glsl camera_path_vshader.glsl camera_path_fshader.glsl virtual_camera_fshader.glsl virtual_camera_vshader.glsl main.cpp)

target_link_libraries(project-matterhorn ${COMMON_LIBS})
target_stringify_shader(project-matterhorn terrain_vshader)
target_stringify_shader(project-matterhorn terrain_fshader)
target_stringify_shader(project-matterhorn water_vshader)
target_stringify_shader(project-matterhorn water_fshader)
target_stringify_shader(project-matterhorn noise_vshader)
target_stringify_shader(project-matterhorn noise_fshader)
target_stringify_shader(project-matterhorn skybox_vshader)
target_stringify_shader(project-matterhorn skybox_fshader)
target_stringify_shader(project-matterhorn shadow_fshader)
target_stringify_shader(project-matterhorn camera_path_fshader)
target_stringify_shader(project-matterhorn camera_path_vshader)
target_stringify_shader(project-matterhorn virtual_camera_vshader)
target_stringify_shader(project-matterhorn virtual_camera_fshader)
target_deploy_file(project-matterhorn textures/grass.tga)
target_deploy_file(project-matterhorn textures/rock.tga)
target_deploy_file(project-matterhorn textures/snow.tga)
target_deploy_file(project-matterhorn textures/sand.tga)
target_deploy_file(project-matterhorn textures/skybox_xneg.tga)
target_deploy_file(project-matterhorn textures/skybox_xpos.tga)
target_deploy_file(project-matterhorn textures/skybox_yneg.tga)
target_deploy_file(project-matterhorn textures/skybox_ypos.tga)
target_deploy_file(project-matterhorn textures/skybox_zneg.tga)
target_deploy_file(project-matterhorn textures/skybox_zpos.tga)
