# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Kokaku/Documents/EPFL/ba6/compgraph/project/operation-matterhorn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Kokaku/Documents/EPFL/ba6/compgraph/project/operation-matterhorn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Kokaku/Documents/EPFL/ba6/compgraph/project/operation-matterhorn/CMakeFiles /Users/Kokaku/Documents/EPFL/ba6/compgraph/project/operation-matterhorn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Kokaku/Documents/EPFL/ba6/compgraph/project/operation-matterhorn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project-matterhorn

# Build rule for target.
project-matterhorn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project-matterhorn
.PHONY : project-matterhorn

# fast build rule for target.
project-matterhorn/fast:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/build
.PHONY : project-matterhorn/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_camera_path_fshader

# Build rule for target.
stringify_project-matterhorn_camera_path_fshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_camera_path_fshader
.PHONY : stringify_project-matterhorn_camera_path_fshader

# fast build rule for target.
stringify_project-matterhorn_camera_path_fshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_camera_path_fshader.dir/build.make CMakeFiles/stringify_project-matterhorn_camera_path_fshader.dir/build
.PHONY : stringify_project-matterhorn_camera_path_fshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_camera_path_vshader

# Build rule for target.
stringify_project-matterhorn_camera_path_vshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_camera_path_vshader
.PHONY : stringify_project-matterhorn_camera_path_vshader

# fast build rule for target.
stringify_project-matterhorn_camera_path_vshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_camera_path_vshader.dir/build.make CMakeFiles/stringify_project-matterhorn_camera_path_vshader.dir/build
.PHONY : stringify_project-matterhorn_camera_path_vshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_noise_fshader

# Build rule for target.
stringify_project-matterhorn_noise_fshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_noise_fshader
.PHONY : stringify_project-matterhorn_noise_fshader

# fast build rule for target.
stringify_project-matterhorn_noise_fshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_noise_fshader.dir/build.make CMakeFiles/stringify_project-matterhorn_noise_fshader.dir/build
.PHONY : stringify_project-matterhorn_noise_fshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_noise_vshader

# Build rule for target.
stringify_project-matterhorn_noise_vshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_noise_vshader
.PHONY : stringify_project-matterhorn_noise_vshader

# fast build rule for target.
stringify_project-matterhorn_noise_vshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_noise_vshader.dir/build.make CMakeFiles/stringify_project-matterhorn_noise_vshader.dir/build
.PHONY : stringify_project-matterhorn_noise_vshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_shadow_fshader

# Build rule for target.
stringify_project-matterhorn_shadow_fshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_shadow_fshader
.PHONY : stringify_project-matterhorn_shadow_fshader

# fast build rule for target.
stringify_project-matterhorn_shadow_fshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_shadow_fshader.dir/build.make CMakeFiles/stringify_project-matterhorn_shadow_fshader.dir/build
.PHONY : stringify_project-matterhorn_shadow_fshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_skybox_fshader

# Build rule for target.
stringify_project-matterhorn_skybox_fshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_skybox_fshader
.PHONY : stringify_project-matterhorn_skybox_fshader

# fast build rule for target.
stringify_project-matterhorn_skybox_fshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_skybox_fshader.dir/build.make CMakeFiles/stringify_project-matterhorn_skybox_fshader.dir/build
.PHONY : stringify_project-matterhorn_skybox_fshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_skybox_vshader

# Build rule for target.
stringify_project-matterhorn_skybox_vshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_skybox_vshader
.PHONY : stringify_project-matterhorn_skybox_vshader

# fast build rule for target.
stringify_project-matterhorn_skybox_vshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_skybox_vshader.dir/build.make CMakeFiles/stringify_project-matterhorn_skybox_vshader.dir/build
.PHONY : stringify_project-matterhorn_skybox_vshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_terrain_fshader

# Build rule for target.
stringify_project-matterhorn_terrain_fshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_terrain_fshader
.PHONY : stringify_project-matterhorn_terrain_fshader

# fast build rule for target.
stringify_project-matterhorn_terrain_fshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_terrain_fshader.dir/build.make CMakeFiles/stringify_project-matterhorn_terrain_fshader.dir/build
.PHONY : stringify_project-matterhorn_terrain_fshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_terrain_vshader

# Build rule for target.
stringify_project-matterhorn_terrain_vshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_terrain_vshader
.PHONY : stringify_project-matterhorn_terrain_vshader

# fast build rule for target.
stringify_project-matterhorn_terrain_vshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_terrain_vshader.dir/build.make CMakeFiles/stringify_project-matterhorn_terrain_vshader.dir/build
.PHONY : stringify_project-matterhorn_terrain_vshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_virtual_camera_fshader

# Build rule for target.
stringify_project-matterhorn_virtual_camera_fshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_virtual_camera_fshader
.PHONY : stringify_project-matterhorn_virtual_camera_fshader

# fast build rule for target.
stringify_project-matterhorn_virtual_camera_fshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_virtual_camera_fshader.dir/build.make CMakeFiles/stringify_project-matterhorn_virtual_camera_fshader.dir/build
.PHONY : stringify_project-matterhorn_virtual_camera_fshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_virtual_camera_vshader

# Build rule for target.
stringify_project-matterhorn_virtual_camera_vshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_virtual_camera_vshader
.PHONY : stringify_project-matterhorn_virtual_camera_vshader

# fast build rule for target.
stringify_project-matterhorn_virtual_camera_vshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_virtual_camera_vshader.dir/build.make CMakeFiles/stringify_project-matterhorn_virtual_camera_vshader.dir/build
.PHONY : stringify_project-matterhorn_virtual_camera_vshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_water_fshader

# Build rule for target.
stringify_project-matterhorn_water_fshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_water_fshader
.PHONY : stringify_project-matterhorn_water_fshader

# fast build rule for target.
stringify_project-matterhorn_water_fshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_water_fshader.dir/build.make CMakeFiles/stringify_project-matterhorn_water_fshader.dir/build
.PHONY : stringify_project-matterhorn_water_fshader/fast

#=============================================================================
# Target rules for targets named stringify_project-matterhorn_water_vshader

# Build rule for target.
stringify_project-matterhorn_water_vshader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringify_project-matterhorn_water_vshader
.PHONY : stringify_project-matterhorn_water_vshader

# fast build rule for target.
stringify_project-matterhorn_water_vshader/fast:
	$(MAKE) -f CMakeFiles/stringify_project-matterhorn_water_vshader.dir/build.make CMakeFiles/stringify_project-matterhorn_water_vshader.dir/build
.PHONY : stringify_project-matterhorn_water_vshader/fast

#=============================================================================
# Target rules for targets named update_opengp

# Build rule for target.
update_opengp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 update_opengp
.PHONY : update_opengp

# fast build rule for target.
update_opengp/fast:
	$(MAKE) -f CMakeFiles/update_opengp.dir/build.make CMakeFiles/update_opengp.dir/build
.PHONY : update_opengp/fast

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

CameraPath.o: CameraPath.cpp.o
.PHONY : CameraPath.o

# target to build an object file
CameraPath.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/CameraPath.cpp.o
.PHONY : CameraPath.cpp.o

CameraPath.i: CameraPath.cpp.i
.PHONY : CameraPath.i

# target to preprocess a source file
CameraPath.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/CameraPath.cpp.i
.PHONY : CameraPath.cpp.i

CameraPath.s: CameraPath.cpp.s
.PHONY : CameraPath.s

# target to generate assembly for a file
CameraPath.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/CameraPath.cpp.s
.PHONY : CameraPath.cpp.s

Grid.o: Grid.cpp.o
.PHONY : Grid.o

# target to build an object file
Grid.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Grid.cpp.o
.PHONY : Grid.cpp.o

Grid.i: Grid.cpp.i
.PHONY : Grid.i

# target to preprocess a source file
Grid.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Grid.cpp.i
.PHONY : Grid.cpp.i

Grid.s: Grid.cpp.s
.PHONY : Grid.s

# target to generate assembly for a file
Grid.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Grid.cpp.s
.PHONY : Grid.cpp.s

HeightMap.o: HeightMap.cpp.o
.PHONY : HeightMap.o

# target to build an object file
HeightMap.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/HeightMap.cpp.o
.PHONY : HeightMap.cpp.o

HeightMap.i: HeightMap.cpp.i
.PHONY : HeightMap.i

# target to preprocess a source file
HeightMap.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/HeightMap.cpp.i
.PHONY : HeightMap.cpp.i

HeightMap.s: HeightMap.cpp.s
.PHONY : HeightMap.s

# target to generate assembly for a file
HeightMap.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/HeightMap.cpp.s
.PHONY : HeightMap.cpp.s

Shader.o: Shader.cpp.o
.PHONY : Shader.o

# target to build an object file
Shader.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Shader.cpp.o
.PHONY : Shader.cpp.o

Shader.i: Shader.cpp.i
.PHONY : Shader.i

# target to preprocess a source file
Shader.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Shader.cpp.i
.PHONY : Shader.cpp.i

Shader.s: Shader.cpp.s
.PHONY : Shader.s

# target to generate assembly for a file
Shader.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Shader.cpp.s
.PHONY : Shader.cpp.s

ShaderProgram.o: ShaderProgram.cpp.o
.PHONY : ShaderProgram.o

# target to build an object file
ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/ShaderProgram.cpp.o
.PHONY : ShaderProgram.cpp.o

ShaderProgram.i: ShaderProgram.cpp.i
.PHONY : ShaderProgram.i

# target to preprocess a source file
ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/ShaderProgram.cpp.i
.PHONY : ShaderProgram.cpp.i

ShaderProgram.s: ShaderProgram.cpp.s
.PHONY : ShaderProgram.s

# target to generate assembly for a file
ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/ShaderProgram.cpp.s
.PHONY : ShaderProgram.cpp.s

ShadowMap.o: ShadowMap.cpp.o
.PHONY : ShadowMap.o

# target to build an object file
ShadowMap.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/ShadowMap.cpp.o
.PHONY : ShadowMap.cpp.o

ShadowMap.i: ShadowMap.cpp.i
.PHONY : ShadowMap.i

# target to preprocess a source file
ShadowMap.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/ShadowMap.cpp.i
.PHONY : ShadowMap.cpp.i

ShadowMap.s: ShadowMap.cpp.s
.PHONY : ShadowMap.s

# target to generate assembly for a file
ShadowMap.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/ShadowMap.cpp.s
.PHONY : ShadowMap.cpp.s

Skybox.o: Skybox.cpp.o
.PHONY : Skybox.o

# target to build an object file
Skybox.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Skybox.cpp.o
.PHONY : Skybox.cpp.o

Skybox.i: Skybox.cpp.i
.PHONY : Skybox.i

# target to preprocess a source file
Skybox.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Skybox.cpp.i
.PHONY : Skybox.cpp.i

Skybox.s: Skybox.cpp.s
.PHONY : Skybox.s

# target to generate assembly for a file
Skybox.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Skybox.cpp.s
.PHONY : Skybox.cpp.s

Texture.o: Texture.cpp.o
.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i
.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s
.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

Window.o: Window.cpp.o
.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i
.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s
.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/Window.cpp.s
.PHONY : Window.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/project-matterhorn.dir/build.make CMakeFiles/project-matterhorn.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... project-matterhorn"
	@echo "... rebuild_cache"
	@echo "... stringify_project-matterhorn_camera_path_fshader"
	@echo "... stringify_project-matterhorn_camera_path_vshader"
	@echo "... stringify_project-matterhorn_noise_fshader"
	@echo "... stringify_project-matterhorn_noise_vshader"
	@echo "... stringify_project-matterhorn_shadow_fshader"
	@echo "... stringify_project-matterhorn_skybox_fshader"
	@echo "... stringify_project-matterhorn_skybox_vshader"
	@echo "... stringify_project-matterhorn_terrain_fshader"
	@echo "... stringify_project-matterhorn_terrain_vshader"
	@echo "... stringify_project-matterhorn_virtual_camera_fshader"
	@echo "... stringify_project-matterhorn_virtual_camera_vshader"
	@echo "... stringify_project-matterhorn_water_fshader"
	@echo "... stringify_project-matterhorn_water_vshader"
	@echo "... update_opengp"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... CameraPath.o"
	@echo "... CameraPath.i"
	@echo "... CameraPath.s"
	@echo "... Grid.o"
	@echo "... Grid.i"
	@echo "... Grid.s"
	@echo "... HeightMap.o"
	@echo "... HeightMap.i"
	@echo "... HeightMap.s"
	@echo "... Shader.o"
	@echo "... Shader.i"
	@echo "... Shader.s"
	@echo "... ShaderProgram.o"
	@echo "... ShaderProgram.i"
	@echo "... ShaderProgram.s"
	@echo "... ShadowMap.o"
	@echo "... ShadowMap.i"
	@echo "... ShadowMap.s"
	@echo "... Skybox.o"
	@echo "... Skybox.i"
	@echo "... Skybox.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

